# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-Monta
version:      0.01
version_from: lib/Template/Plugin/Monta.pm
installdirs:  site
requires:
    Acme::Monta:                   0
    Template:                      2.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.29
